# Generated by Django 5.0.2 on 2024-02-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invigilator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invigilator',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/Invigilator/'),
        ),
    ]
