# Generated by Django 5.0.2 on 2024-02-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_department_student_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile_pic/Student/'),
        ),
    ]
