# Generated by Django 5.0.2 on 2024-02-15 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_examvenue_room_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examvenue',
            name='room_no',
        ),
        migrations.CreateModel(
            name='ExamRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.examvenue')),
            ],
        ),
    ]
