# Generated by Django 5.0.2 on 2024-02-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_examvenue_room_no_examroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examvenue',
            name='no_of_seats',
        ),
        migrations.AddField(
            model_name='examroom',
            name='no_of_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
