# Generated by Django 5.0.2 on 2024-02-16 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_course_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtimetable',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.semester'),
        ),
    ]
