# Generated by Django 5.0.2 on 2024-02-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_exam_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
