# Generated by Django 5.0.2 on 2024-02-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_exam_date_alter_exam_end_time_alter_exam_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(),
        ),
    ]
