# Generated by Django 5.0.2 on 2024-02-16 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_exam_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.examvenue'),
        ),
    ]
