# Generated by Django 5.0.2 on 2024-02-16 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_exam_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='day_of_week',
        ),
    ]
