# Generated by Django 5.0.2 on 2024-02-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_course_options_alter_exam_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='type',
            field=models.CharField(choices=[('paper', 'Paper Exam'), ('cbt', 'CBT Exam')], default='Paper Exam', max_length=20),
        ),
    ]
