# Generated by Django 5.0.2 on 2024-02-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_exam_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examvenue',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
