# Generated by Django 5.0.2 on 2024-02-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_adminuserconfig_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='type',
            field=models.CharField(choices=[('Paper Exam', 'Paper Exam'), ('CBT', 'CBT')], default='paper', max_length=20),
        ),
    ]
